services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password123
    ports:
      - "1433:1433"
    networks:
      - sqlnet
    volumes:
      - mssql_data:/var/opt/mssql

  dotnet_app:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: dotnet_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      bash -c "dotnet build && dotnet run"
    depends_on:
      - mssql
    networks:
      - sqlnet
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=master;User Id=sa;Password=YourStrong!Password123;

networks:
  sqlnet:
    driver: bridge

volumes:
  mssql_data:
    driver: local
